services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "1323:1323"
    command: sh -c "go build -o back && ./back"